# Generated by Django 5.1.6 on 2025-02-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('paga', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipoprioridade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipodespesa')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
